name: 'release'

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish-game-launcher:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
        include:
          - platform: macos-latest
            rust-targets: 'aarch64-apple-darwin, x86_64-apple-darwin'
            tauri-args: '--target universal-apple-darwin'

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust-targets }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: yarn install

      - name: Determine Tag or Branch
        run: |
          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "IS_TAG=true" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
            echo "IS_TAG=false" >> $GITHUB_ENV
          fi

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          args: ${{ matrix.tauri-args }}
          tagName: ${{ env.RELEASE_VERSION }}
          releaseName: ${{ env.IS_TAG && 'Release ' || 'Pre-Release ' }}${{ env.RELEASE_VERSION }}
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: ${{ !env.IS_TAG }}
          prerelease: ${{ !env.IS_TAG }}
